# Generated by Django 4.2.9 on 2024-04-15 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_blogcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontent",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
