# Generated by Django 4.2.9 on 2024-04-15 09:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_blogcontent_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontent",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
