# Generated by Django 4.2.9 on 2024-04-19 00:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_blogcontent_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_content",
                    ckeditor_uploader.fields.RichTextUploadingField(),
                ),
                ("draft_content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("edit_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Page",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_content",
                    ckeditor_uploader.fields.RichTextUploadingField(),
                ),
                ("draft_content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("edit_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page",
            },
        ),
        migrations.DeleteModel(
            name="BlogContent",
        ),
    ]
