# Generated by Django 4.2.9 on 2024-04-19 01:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_contactpage_homepage_delete_blogcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="draft_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="published_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="draft_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="published_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
